export * as answer from "./answer.svg";
export * as check from "./check.svg";
export * as copy from "./copy.svg";
export * as delete from "./delete.svg";
export * as emptyQuestions from "./emptyQuestions.svg";
export * as googleIcon from "./googleIcon.svg";
export * as illustration from "./illustration.svg";
export * as like from "./like.svg";
export * as logo from "./logo.svg";
