import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  let env = process.env.NODE_ENV;

  console.log(env);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
};

export default Home;
